#!/system/xbin/bash
clear
blue='\e[1;34m'
green='\e[1;32m'
purple='[1;35m'
cyan='\e[1;36m'
red='\e[1;31m'
white='\e[1;37m'
yellow='\e[1;33m'
sleep 1
echo "\033[32;1m========================================"
toilet -f standard -F gay "HACKBANK"
echo "\033[31;1m========================================"
echo ""
echo "Author : " Mr.TamfanX"
" Team : " PasarGintungBukanEmpang"
echo " Kontak Me : " 081272959872"
" Pesan : "Jangan Di Salah Gunakan Dan Disebar :) Karena Nanti Dosa Tanggung Sendiri:)"
sleep 1
echo "ThanksTo: PasirGintungHack"
echo "gkc"
echo "\033[33;1m========================================"
echo ""

echo ="Pilih Nama Bank Kalian:BCA,BRI,BNI"
read p;
sleep 1
: "BIGipServerpool_bri.co.id_new=963121836.47873.0000";
sleep 2
"User agen : Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.4) Gecko/20100101 Firefox/4.0";
sleep 3 :
"_ga=GA1.3.1584158838.1583437584;
echo ="Masukkan Nama Anda";
read p;
sleep 4:
"_gid=GA1.3.1524813014.1583437584";
echo ="Masukkan No Rek Anda"
read p;
sleep 5
JSESSIONID=7F0B30A976393B4492F2F99097904977.liferay2;

sleep 6 : "GET /mobile_banking HTTP/1.1
Host: bri.co.id
Connection: keep-alive
Upgrade-Insecure-Requests: 1
User-Agent: Mozilla/5.0 (X11; U; Linux i686; en-US; rv:1.9.0.4) Gecko/20100101 Firefox/4.0
Sec-Fetch-Dest: document
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,/;q=0.8,application/signed-exchange;v=b3;q=0.9
dnt: 1
X-Requested-With: com.digidemic.browserbot
Sec-Fetch-Site: none
Sec-Fetch-Mode: navigate
Sec-Fetch-User: ?1
Accept-Encoding: gzip, deflate
Accept-Language: id,en-US;q=0.9,en;q=0.8";

echo ="Sebutkan Nominal Minimal hanya bisa mentransfer sebanyak Rp.200.000,-
read p;
sleep 1
sleep 2
sleep 3
sleep 4
sleep 5
sleep 6
sleep 7
sleep 8
sleep 9
echo ="Transfer Rp 200.000,- sukses mau coba lagi"
sleep 1
sleep 2
echo ="Cukup 1 hari hanya dapat mentransfer Rp. 200.000.-"
read p;
sleep 1
sleep 2
sleep 3
sleep 4
sleep 5

echo "Pesan:Gunakanlah Dengan Sebaik Mungkin Jangan Beritahu Script Ini Kepada Orang Lain:)"
sleep 1
sleep 2
echo "ThankSToo"
echo "GintungTeamHack"
sleep 1
sleep 2
echo "Baca Pesannya!!
Gunakan uang sebaik-baiknya :*"
sleep 1
sleep 2
